# Generated by Django 5.2.6 on 2025-10-01 03:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allowed_students',
            field=models.ManyToManyField(blank=True, related_name='allowed_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Học sinh được phép làm bài'),
        ),
    ]
