# Generated by Django 5.2.6 on 2025-10-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_allowed_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='allowed_students',
        ),
        migrations.AddField(
            model_name='quiz',
            name='access_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Mã tham gia'),
        ),
    ]
