# Generated by Django 5.2.5 on 2025-10-01 05:17

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_quiz_allowed_students_quiz_access_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allowed_students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='allowed_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Học sinh được phép'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 1, 5, 17, 32, 437094, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
