# Generated by Django 5.2.5 on 2025-10-01 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_allowed_students_alter_quiz_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Nếu được chọn, tất cả học sinh sẽ thấy đề thi này. Nếu không, chỉ học sinh tham gia bằng mã code mới thấy.', verbose_name='Công khai?'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Là đáp án đúng?'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question', verbose_name='Câu hỏi'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Nội dung đáp án'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Dễ'), ('MEDIUM', 'Trung bình'), ('HARD', 'Khó')], max_length=10, verbose_name='Độ khó'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.subject', verbose_name='Môn học'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Nội dung câu hỏi'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='allowed_students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='allowed_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Học sinh được phép tham gia (cho đề riêng tư)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Thời gian làm bài (tính bằng phút)', verbose_name='Thời gian làm bài'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(verbose_name='Thời gian kết thúc'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(to='quiz.question', verbose_name='Các câu hỏi'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(verbose_name='Thời gian bắt đầu'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subject', verbose_name='Môn học'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề đề thi'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Tên môn học'),
        ),
    ]
