# Generated by Django 5.0.7 on 2025-11-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_is_public_alter_answer_is_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer_text',
            field=models.TextField(blank=True, null=True, verbose_name='Đáp án đúng (cho tự luận)'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'Câu hỏi nhiều lựa chọn'), ('TRUE_FALSE', 'Câu hỏi Đúng/Sai'), ('SHORT_ANSWER', 'Câu tự luận ngắn'), ('SINGLE_CHOICE', 'Câu hỏi một lựa chọn')], default='SINGLE_CHOICE', max_length=20, verbose_name='Loại câu hỏi'),
        ),
    ]
