# Generated by Django 5.2.5 on 2025-11-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_question_correct_answer_text_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allow_multiple_attempts',
            field=models.BooleanField(default=False, help_text='Nếu được chọn, học sinh có thể thi đề này nhiều lần. Nếu không, mỗi học sinh chỉ được thi 1 lần.', verbose_name='Cho phép thi nhiều lần'),
        ),
    ]
