# Generated by Django 5.2.5 on 2025-11-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_quiz_allow_multiple_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Giải thích này sẽ hiển thị sau khi học sinh hoàn thành bài thi.', null=True, verbose_name='Giải thích đáp án'),
        ),
    ]
