# Generated by Django 5.2.5 on 2025-12-03 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0009_question_explanation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('TECHNICAL', 'Sự cố kỹ thuật'), ('QUESTION', 'Câu hỏi về đề thi'), ('ACCOUNT', 'Vấn đề tài khoản'), ('FEEDBACK', 'Góp ý, phản hồi'), ('OTHER', 'Khác')], default='QUESTION', max_length=20, verbose_name='Loại yêu cầu')),
                ('subject', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='Phản hồi từ quản trị viên')),
                ('status', models.CharField(choices=[('OPEN', 'Đang chờ xử lý'), ('IN_PROGRESS', 'Đang xử lý'), ('RESOLVED', 'Đã giải quyết'), ('CLOSED', 'Đã đóng')], default='OPEN', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('admin', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.quiz', verbose_name='Liên quan đến đề thi')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
            ],
            options={
                'verbose_name': 'Yêu cầu hỗ trợ',
                'verbose_name_plural': 'Yêu cầu hỗ trợ',
                'ordering': ['-created_at'],
            },
        ),
    ]
