# Generated by Django 5.2.5 on 2025-12-03 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Đã đọc?'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian phản hồi'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Người phản hồi'),
        ),
    ]
